### ISSUE TITLE
Nav Bar responsive issue

### ISSUE THREAD

**Issue by LoopGlitch26** [SOACodeRoom/Summer-Hacks#35]
Original view:

![Screenshot 2021-05-04 at 5 40 28 AM](https://user-images.githubusercontent.com/53336715/116947939-e11c4280-ac32-11eb-9bc6-befedb62c82f.png)

Issue:

https://user-images.githubusercontent.com/53336715/116947954-e5e0f680-ac32-11eb-9c89-e14ca1158458.mov

How It should be:

![Screenshot 2021-05-04 at 5 42 48 AM](https://user-images.githubusercontent.com/53336715/116947961-e8dbe700-ac32-11eb-90fa-0140ce1bc752.png)

**Comment by LoopGlitch26** [comment]
@RahulAnand442001 if you're interested to resolve this issue, try this:
https://codemyui.com/pure-css-fullscreen-navigation-menu/

**Comment by saswatsamal** [comment]
I tried debugging it and found there's a problem with `z-index` .
I removed the `bootstrap.min.css` and found it all working well. But couldn't able to fix it. If @RahulAnand442001 will look into the matter, then it will be great.

**Comment by RahulAnand442001** [comment]
Instead of using a bootstrap.min.css please use the Bootstrap CDN Links (both css and js links).

When you mention explicitly the z-index.. You must not have given the specificity.
Bootstrap css has higher specificity than our css.


Here ia the 2 thing that need ti be changed :

1) Always place your own CSS link below any of the global Css framework links like bootstrap or tailwind CSS.

This will override the new css property.

E. G : inside the <head></head> tag
Write like this:
<link:css>bootstrap link </>
<link>your css link </>


2) inside the Css file ( what we have written) wherever you have mentioned the z-index, give a importance level to it.

E. G.

.nav-links{
position: absolute
z-index: 100 ! important
}

Note:
Z-index works when a html tag/component is relative positioning
like position-absolute or position-relative.



Hope this will work.
